# Usamos imagen oficial Python ligera
FROM python:3.11-slim

# Crear directorio de la app
WORKDIR /app

# Copiar archivos de requirements e instalar dependencias
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente
COPY ./app ./app

# Exponer puerto (el que usa FastAPI por defecto)
EXPOSE 8000

# Comando para iniciar el servidor
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
